spring.application.name=CRUD_Vehiculo

server.port=8004

#Ruta de conexion hacia la bd de oracle
spring.datasource.url=jdbc:mysql://enucom-db.c9u2okuumhzu.us-east-2.rds.amazonaws.com:3306/vehiculos_db?useSSL=false&serverTimeZone=UTC
#Usuario de la bd dode se conectara Spring
spring.datasource.username=admin
spring.datasource.password=ZeFc-0w419dWv$P

#Configuracion del hibernate
spring.jpa.hibernate.ddl-auto=update
#Driver de oracle
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Dialecto de hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Mostramos sql en consola
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.show-sql=true