spring.application.name=CRUD_Vehiculo
server.port=8003


#ruta de conexion hacia la bd de oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
#usuario de la bd donde se conectrara Spring
spring.datasource.username=LUIS16
spring.datasource.password=luis

#configuracion del hibernate
spring.jpa.hibernate.ddl-auto=update
#driver de oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#tipo de bd
spring.jpa.database=oracle
#Dialecto de hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#Mostramos sql en consola
spring.jpa.properties.hibernate.format-sql=true